version: '3.8'

services:
  pizzeria:
    image: donfias/my_web_projects:latest
    container_name: pizzeria
    ports:
      - "8020:8080"
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - sqlite_data:/app/data
volumes:
  sqlite_data: